sudo: required
services:
  - docker
language: node_js
cache:
  directories:
    - ~/.npm
    - "client/node_modules"
node_js:
  - "8"
install:
  - npm install
script:
 - npm run build:travis_ci
#  - npm run compile
