export const INCREMENT_LIKES = 'INCREMENT_LIKES';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const SINGLE_POST = 'SINGLE_POST';
export const ALL_POSTS = 'ALL_POSTS';